# Generated by Django 4.0.3 on 2022-04-12 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userbase',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userbase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userbase',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='userbase',
            name='town_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userbase',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
