# Generated by Django 4.0.3 on 2022-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbase_address_line_1_userbase_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='town_city',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='updated',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
