# Generated by Django 4.0.3 on 2022-04-15 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userbase_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='address_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userbase',
            name='address_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userbase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userbase',
            name='postcode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userbase',
            name='town_city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userbase',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
